
import java.awt.Color;
import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author JUANN
 */
public class VerProducto extends javax.swing.JFrame {

    /**
     * Creates new form VerProducto
     */
    private Dimension size;
    private String codigo = "";
    private int width, height;

    public VerProducto(String codigo, ResultSet rs) throws MalformedURLException, SQLException, InterruptedException {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.getContentPane().setBackground(Color.decode("#FFFFFF"));
        size = Toolkit.getDefaultToolkit().getScreenSize();

        width = Toolkit.getDefaultToolkit().getScreenSize().width;
        height = Toolkit.getDefaultToolkit().getScreenSize().height;

        this.setSize(Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height);

        this.setLayout(null);
        try {

         
            jLabel7.setLocation(this.getWidth() / 2 - jLabel7.getWidth() - 50, this.getHeight() / 2 - jLabel7.getHeight() / 2);

            jLabel5.setLocation(jLabel7.getLocation().x + jLabel7.getHeight() + 30, jLabel7.getLocation().y);
            jLabel6.setLocation(jLabel7.getLocation().x + jLabel7.getHeight() + 30, jLabel5.getLocation().y + jLabel5.getHeight() + 8);
            
            System.out.println("" + rs.getString(1));
            jLabel5.setText("" + rs.getString(1));
            jLabel6.setText("<html>Precio: $" + rs.getString(2) + " <br><br> En Stock: " + rs.getString(3));
          

            String ruta = rs.getString(4);
            ImageIcon icono = new ImageIcon(new URL(ruta));
            jLabel7.setIcon(new ImageIcon(icono.getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT)));
            Thread.sleep(5000);
            cerrar();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error");
        }

    }
    
    void cerrar(){
       this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 3, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("jLabel5");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel5.setAutoscrolls(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 750, 40));

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 3, 29)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("jLabel4");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel6.setMaximumSize(new java.awt.Dimension(350, 220));
        jLabel6.setMinimumSize(new java.awt.Dimension(350, 220));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 380, 220));

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 2, 24)); // NOI18N
        jLabel7.setMinimumSize(new java.awt.Dimension(200, 200));
        jLabel7.setName(""); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 200, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            this.dispose();
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
